// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlsCWw5OzHMRb-cGFqp7XdOtDKKe5AoA4',
    appId: '1:1063076857771:web:fb1b4f202fb195d23134ee',
    messagingSenderId: '1063076857771',
    projectId: 'wsfm-69551',
    authDomain: 'wsfm-69551.firebaseapp.com',
    storageBucket: 'wsfm-69551.firebasestorage.app',
    measurementId: 'G-9XTC4G6JFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFTSo94-6FgMGhV2fPj1nXmgpOAv4oHmA',
    appId: '1:1063076857771:android:1bf46a91418ca6b73134ee',
    messagingSenderId: '1063076857771',
    projectId: 'wsfm-69551',
    storageBucket: 'wsfm-69551.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlsCWw5OzHMRb-cGFqp7XdOtDKKe5AoA4',
    appId: '1:1063076857771:web:72762c455c06af373134ee',
    messagingSenderId: '1063076857771',
    projectId: 'wsfm-69551',
    authDomain: 'wsfm-69551.firebaseapp.com',
    storageBucket: 'wsfm-69551.firebasestorage.app',
    measurementId: 'G-M54RK7ET0E',
  );
}
